UPDATE `creature_template` SET flags_extra = flags_extra | 256 WHERE entry=11583;

DELETE FROM `script_texts` WHERE entry BETWEEN -1409025 AND -1409001;
INSERT INTO `script_texts` VALUES 
('-1409024','Impudent whelps! You\'ve rushed headlong to your own deaths! See now, the master stirs!',NULL,NULL,'Unverschämte Welpen! Ihr seid sehenden Auges dem Tod in die Arme gelaufen! Seht her, der Meister regt sich!',NULL,NULL,NULL,NULL,NULL,'0','1','0','0','majordomo SAY_SUMMON_1'),
('-1409023','Very well, $N.',NULL,NULL,'Nun gut, $N.',NULL,NULL,NULL,NULL,NULL,'0','0','0','0','majordomo SAY_SUMMON_0'),
('-1409022','My flame! Please don\'t take away my flame... ',NULL,NULL,'Ich werde euch nun verlassen. Es ist an der Zeit den Herrn dieses Hauses herbeizurufen. Wenn ihr eine Unterredung mit ihm wünscht, werdet ihr diese mit euren armseligen Leben bezahlen! Solltet ihr es dennoch wagen wollen, so sucht ruhig seine Ruhestätte auf!',NULL,NULL,NULL,NULL,NULL,'8042','1','0','0','ragnaros SAY_ARRIVAL4_MAJ'),
('-1409021','I go now to summon the lord whos house this is. Should you seek an audiance with him your paltry lives will surly be forfit. Nevertheless seek out his lair if you dare!',NULL,NULL,'meine Flamme! Bitte nehmt nicht meine Flamme weg...',NULL,NULL,NULL,NULL,NULL,'0','1','0','0','majordomo SAY_DEFEAT_3'),
('-1409020','Brashly you have come to rest the secrets of the living flame. You will soon regret the recklessness of your quest.',NULL,NULL,'In eurer grenzenlosen Unverfrorenheit wolltet ihr die Geheimnisse der Lebenden Flamme an euch reißen! Schon bald werdet ihr die Leichtsinnigkeit eurer Suche bereuen!',NULL,NULL,NULL,NULL,NULL,'0','1','0','0','majordomo SAY_DEFEAT_2'),
('-1409019','You think you\'ve won already? Perhaps you\'ll need another lesson in pain!',NULL,NULL,'Ihr glaubt also, Ihr hättet schon gewonnen? Mir scheint, dass Ihr noch eine Lektion in Sachen Schmerz braucht!',NULL,NULL,NULL,NULL,NULL,'0','1','0','0','majordomo SAY_LAST_ADD'),
('-1409018','MY PATIENCE IS DWINDLING! COME, GNATS, TO YOUR DEATH!',NULL,NULL,'MEINE GEDULD SCHWINDET! KOMMT SCHMEISSFLIEGEN, DER TOD WARTET!',NULL,NULL,NULL,NULL,NULL,'8048','1','0','0','ragnaros SAY_MAGMABURST'),
('-1409017','DIE INSECT!',NULL,NULL,'STIRB, INSEKT!',NULL,NULL,NULL,NULL,NULL,'8051','1','0','0','ragnaros SAY_KILL'),
('-1409016','TASTE THE FLAMES OF SULFURON!',NULL,NULL,'SPÜRT DIE FLAMMEN VON SULFURON!',NULL,NULL,NULL,NULL,NULL,'8047','1','0','0','ragnaros SAY_WRATH'),
('-1409015','BY FIRE BE PURGED!',NULL,NULL,'DAS FEUER WIRD EUCH LÄUTERN!',NULL,NULL,NULL,NULL,NULL,'8046','1','0','0','ragnaros SAY_HAND'),
('-1409014','YOU CANNOT DEFEAT THE LIVING FLAME! COME YOU MINIONS OF FIRE! COME FORTH YOU CREATURES OF HATE! YOUR MASTER CALLS!',NULL,NULL,'NIEMAND BESIEGT DIE LEBENDE FLAMME! KOMMT IHR DIENER DES FEUERS! VORWÄRTS IHR KREATUREN DES HASSES! EUER MEISTER RUFT EUCH!!',NULL,NULL,NULL,NULL,NULL,'8050','1','0','0','ragnaros SAY_REINFORCEMENTS2'),
('-1409013','COME FORTH, MY SERVANTS! DEFEND YOUR MASTER!',NULL,NULL,'Kommt herbei, meine Diener! Verteidigt euren Herren!',NULL,NULL,NULL,NULL,NULL,'8049','1','0','0','ragnaros SAY_REINFORCEMENTS1'),
('-1409012','NOW FOR YOU, INSECTS. BOLDLY YOU SAUGHT THE POWER OF RAGNAROS NOW YOU SHALL SEE IT FIRST HAND.',NULL,NULL,'NUN ZU EUCH, INSEKTEN! MUTIG HABT IHR NACH DER MACHT VON RAGNAROS GESUCHT. NUN SOLLT IHR SIE AUS ERSTER HAND ERFAHREN!',NULL,NULL,NULL,NULL,NULL,'8045','1','0','0','ragnaros SAY_ARRIVAL5_RAG'),
('-1409011','FOOL! YOU ALLOWED THESE INSECTS TO RUN RAMPANT THROUGH THE HALLOWED CORE, AND NOW YOU LEAD THEM TO MY VERY LAIR? YOU HAVE FAILED ME, EXECUTUS! JUSTICE SHALL BE MET, INDEED!',NULL,NULL,'NARR! DU LÄSST ES ZU, DAS SICH DIESE INSEKTEN IM GEHEILIGTEN KERN HERUMTREIBEN? UND NUN FÜHRST DU SIE AUCH NOCH IN MEINE HEIMSTÄTTE? DU ENTTÄUSCHT MICH, EXECUTUS! IN DER TAT WERDE ICH GERECHTIGKEIT WALTEN LASSEN!',NULL,NULL,NULL,NULL,NULL,'8044','1','0','0','ragnaros SAY_ARRIVAL3_RAG'),
('-1409010','These mortal infidels, my lord! They have invaded your sanctum, and seek to steal your secrets!',NULL,NULL,'Diese ungläubigen Sterblichen, mein Fürst! Sie drangen in Euer Allerheiligstes ein und trachteten danach Eure Geheimnisse zu stehlen!',NULL,NULL,NULL,NULL,NULL,'8041','1','0','0','ragnaros SAY_ARRIVAL2_MAJ'),
('-1409009','TOO SOON! YOU HAVE AWAKENED ME TOO SOON, EXECUTUS! WHAT IS THE MEANING OF THIS INTRUSION?',NULL,NULL,'ZU FRÜH! IHR HABT MICH ZU FRÜH ERWECKT, EXEKUTUS! WAS HAT DIESE STÖRUNG ZU BEDEUTEN???',NULL,NULL,NULL,NULL,NULL,'8043','1','0','0','ragnaros SAY_ARRIVAL1_RAG'),
('-1409008','Behold Ragnaros, the Firelord! He who was ancient when this world was young! Bow before him, mortals! Bow before your ending!',NULL,NULL,'Seht Ragnaros - den Feuerfürsten! Er, der schon uralt war, als eure Welt noch jung war. Verneigt euch vor ihm, Sterbliche! Verneigt euch vor eurem Untergang!',NULL,NULL,NULL,NULL,NULL,'8040','1','0','0','ragnaros SAY_SUMMON_MAJ'),
('-1409007','Impossible! Stay your attack mortals! I submitt! I submitt!',NULL,NULL,'Unmöglich! Haltet ein Sterbliche! Haltet ein! Ich gebe auf! Ich gebe auf! In eurer grenzenlosen Unverfrorenheit wolltet ihr die Geheimnisse der Lebenden Flamme an euch reißen! Schon bald werdet ihr die Leichtsinnigkeit eurer Suche bereuen! Ich werde euch nun verlassen, es ist an der Zeit den Herren dieses Hauses herbeizurufen. Wenn ihr eine Unterredung mit ihm wünscht werdet ihr diese mit eurem armseligen Leben bezahlen! Solltet ihr es dennoch wagen wollen, so sucht ruhig seine Ruhestätte auf!',NULL,NULL,NULL,NULL,NULL,'8038','1','0','0','majordomo SAY_DEFEAT_1'),
('-1409006','Burn mortals! Burn for this transgression!',NULL,NULL,'Brennt, Sterbliche! Brennt für diesen Frevel!',NULL,NULL,NULL,NULL,NULL,'8036','1','0','0','majordomo SAY_SPECIAL'),
('-1409005','Ashes to Ashes!',NULL,NULL,'Asche zu Asche!',NULL,NULL,NULL,NULL,NULL,'8037','1','0','0','majordomo SAY_SLAY'),
('-1409004','The runes of warding have been destroyed! Hunt down the infedels my bretheren.',NULL,NULL,'Die Schutzrunen wurden zerstört! Vernichtet alle Ungläubigen, meine Brüder!',NULL,NULL,NULL,NULL,NULL,'8039','6','0','0','majordomo SAY_SPAWN'),
('-1409003','Reckless mortals, none may challenge the sons of the living flame!',NULL,NULL,'Schwächliche Sterbliche! Niemand fordert die Söhne der Lebenden Flamme heraus!',NULL,NULL,NULL,NULL,NULL,'8035','1','0','0','majordomo SAY_AGGRO'),
('-1409002','%s refuses to die while its master is in trouble.',NULL,NULL,'%s weigert sich zu sterben so lange sein Meister in Schwierigkeiten steckt.',NULL,NULL,NULL,NULL,NULL,'0','2','0','0','core rager EMOTE_LOWHP');